env: "dev"

storage:
  host: "database"
  port: "5432"
  user: "postgres"
  password: "Forgetto2011"
  dbname: "medods"
  sslmode: "disable"

httpserver:
  address: "0.0.0.0:8085"

secret-string: "the-secret-code-which-i-will-use-for-signing-my-jwt-tokens-in-golang"
